
[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

# Environment variables for Firebase (you'll need to set these in Netlify dashboard)
# NEXT_PUBLIC_FIREBASE_API_KEY = "your-api-key"
# NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
# NEXT_PUBLIC_FIREBASE_PROJECT_ID = "your-project-id"
# NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
# NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "123456789"
# NEXT_PUBLIC_FIREBASE_APP_ID = "your-app-id"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
